service: metrolink-less

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "*"
      Resource: "*"

functions:
  AliveHello:
    handler: api/alive/handler.hello
    memorySize: 128
    description: Root method, checking if alive.
    events:
      - http: 
          path: '/'
          method: get
      - http: 
          path: '/'
          method: post

  FetchMetrolink:
    handler: api/dataFetch/fetchMetrolink.fetchMetrolink
    memorySize: 256
    description: Fetch Metrolink data and store in a database.
    events:
      - http: 
          path: '/fetchMetro'
          method: get
      - schedule:
          rate: rate(4 minutes)
          enable: true

  FetchMistakes:
    handler: api/dataFetch/fetchMistakes.fetchMistakes
    memorySize: 256
    description: Fetch spelling mistakes on the info boards, tweet it out.
    events:
      - http: 
          path: '/fetchMistakes'
          method: get

  GetStopNames:
    handler: api/publicData/getStopNames.getStopNames
    memorySize: 128
    description: Get Names
    events:
      - http: 
          path: '/stopNames'
          method: get
          cors: true


  GetStopData:
    handler: api/publicData/getStopData.getStopData
    memorySize: 128
    description: Get Data
    events:
      - http: 
          path: '/stopData/{name}'
          method: get
          cors: true

# resources: # CloudFormation template syntax
#   Resources:
#     Tramstops:
#       Type: AWS::DynamoDB::Table
#       DeletionPolicy: Retain
#       Properties:
#         TableName: Tramstops
#         AttributeDefinitions:
#           - AttributeName: name
#             AttributeType: S
#         KeySchema:
#           - AttributeName: name
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
        