service: metrolink-less

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2
  environment:
    CANDIDATE_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    CANDIDATE_EMAIL_TABLE: "candidate-email-${opt:stage, self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  AliveHello:
    handler: api/alive/handler.hello
    memorySize: 128
    description: Root method, checking if alive.
    events:
      - http: 
          path: '/'
          method: get
      - http: 
          path: '/'
          method: post

  FetchMetrolink:
    handler: api/dataFetch/fetchMetrolink.fetchMetrolink
    memorySize: 128
    description: Fetch Metrolink data and store in a database.
    events:
      - http: 
          path: '/fetchMetro'
          method: get
      - http: 
          path: '/fetchMetro'
          method: post

resources:
  Resources:
    CandidatesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.CANDIDATE_TABLE}